# Generated by Django 6.0.2 on 2026-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('quality', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_sensorr_timesta_d40ba1_idx'), models.Index(fields=['sensor_id', 'timestamp'], name='api_sensorr_sensor__86197d_idx')],
            },
        ),
    ]
