# Generated by Django 6.0.2 on 2026-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='api_sensorr_timesta_d40ba1_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='api_sensorr_sensor__86197d_idx',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='battery_life',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='turbidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='water_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='wave_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='wave_period',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='quality',
            field=models.CharField(default='OK', max_length=50),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='value',
        ),
    ]
