# Generated by Django 6.0.3 on 2026-03-29 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sensorreading_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('sensor_id', models.CharField(blank=True, default='', max_length=100)),
                ('metric', models.CharField(choices=[('water_temperature', 'Vattentemperatur'), ('turbidity', 'Turbiditet'), ('wave_height', 'Våghöjd'), ('wave_period', 'Vågperiod'), ('battery_life', 'Batteri'), ('quality', 'Kvalitet')], max_length=40)),
                ('operator', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('eq', '=')], default='gt', max_length=8)),
                ('threshold_number', models.FloatField(blank=True, null=True)),
                ('threshold_text', models.CharField(blank=True, default='', max_length=80)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('cooldown_minutes', models.PositiveIntegerField(default=15)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('subject_template', models.CharField(default='Larm från Smart Env Monitor: {name}', max_length=200)),
                ('body_template', models.TextField(default='Regel: {name}\nSensor: {sensor_id}\nTid: {timestamp}\nMätvärde: {metric} = {value}\nVillkor: {metric} {operator} {threshold}\n')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='api.sensorreading')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.alertrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
