# Generated by Django 6.0.3 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_sensorreading_unique_together"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(fields=["sensor_id", "timestamp"], name="api_sensorr_sensor__9238f9_idx"),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(fields=["timestamp"], name="api_sensorr_timesta_7d4e8f_idx"),
        ),
    ]
