"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

def _env_bool(key: str, default: bool) -> bool:
    raw = os.getenv(key)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}

def _env_csv(key: str, default: list[str]) -> list[str]:
    raw = os.getenv(key)
    if raw is None:
        return default
    items = [part.strip() for part in raw.split(",")]
    return [item for item in items if item]


def _env_int(key: str, default: int) -> int:
    raw = os.getenv(key)
    if raw is None:
        return default
    try:
        return int(raw.strip())
    except ValueError as exc:
        raise RuntimeError(f"{key} must be an integer") from exc


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = _env_bool("DEBUG", True)

SECRET_KEY = (os.getenv("SECRET_KEY") or "").strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-9rddhf1s1xzyr0!b#5fr@^xggar@!rp*h++j65c^^28s@y5alt"
    else:
        raise RuntimeError("SECRET_KEY is required when DEBUG=False")

ALLOWED_HOSTS = _env_csv("ALLOWED_HOSTS", ["localhost", "127.0.0.1"])
CSRF_TRUSTED_ORIGINS = _env_csv("CSRF_TRUSTED_ORIGINS", [])
MFA_DOMAIN = (os.getenv("MFA_DOMAIN") or (ALLOWED_HOSTS[0] if ALLOWED_HOSTS else "localhost")).strip()
MFA_SITE_TITLE = (os.getenv("MFA_SITE_TITLE") or "Smart Env Monitor").strip()
OIDC_ENABLED = _env_bool("OIDC_ENABLED", False)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'django_prometheus',
    'mfa',
    'api',
    'dashboard',
]
if OIDC_ENABLED:
    INSTALLED_APPS.append("mozilla_django_oidc")

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'backend.request_id.RequestIDMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mfa.middleware.MFAEnforceMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

database_url = (os.getenv("DATABASE_URL") or "").strip()
if database_url:
    parsed = urlparse(database_url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        raise RuntimeError("Only postgres/postgresql DATABASE_URL schemes are supported")
    options = {k: v[0] for k, v in parse_qs(parsed.query).items() if v}
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": (parsed.path or "").lstrip("/"),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or ""),
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
            "OPTIONS": options,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/accounts/login/'
ENABLE_SSO_HEADER_AUTH = _env_bool("ENABLE_SSO_HEADER_AUTH", False)
SSO_HEADER_USERNAME = os.getenv("SSO_HEADER_USERNAME", "X-Forwarded-User")
SSO_HEADER_EMAIL = os.getenv("SSO_HEADER_EMAIL", "X-Forwarded-Email")
AUTHENTICATION_BACKENDS: list[str] = []
if OIDC_ENABLED:
    AUTHENTICATION_BACKENDS.append("backend.auth_backends.OIDCBackend")
AUTHENTICATION_BACKENDS.append("django.contrib.auth.backends.ModelBackend")
if ENABLE_SSO_HEADER_AUTH:
    AUTHENTICATION_BACKENDS.append("backend.auth_backends.TrustedHeaderBackend")

if OIDC_ENABLED:
    OIDC_RP_CLIENT_ID = (os.getenv("OIDC_RP_CLIENT_ID") or "").strip()
    OIDC_RP_CLIENT_SECRET = (os.getenv("OIDC_RP_CLIENT_SECRET") or "").strip()
    OIDC_OP_AUTHORIZATION_ENDPOINT = (os.getenv("OIDC_OP_AUTHORIZATION_ENDPOINT") or "").strip()
    OIDC_OP_TOKEN_ENDPOINT = (os.getenv("OIDC_OP_TOKEN_ENDPOINT") or "").strip()
    OIDC_OP_USER_ENDPOINT = (os.getenv("OIDC_OP_USER_ENDPOINT") or "").strip()
    OIDC_OP_JWKS_ENDPOINT = (os.getenv("OIDC_OP_JWKS_ENDPOINT") or "").strip()
    OIDC_RP_SIGN_ALGO = (os.getenv("OIDC_RP_SIGN_ALGO") or "RS256").strip()
    OIDC_RP_SCOPES = (os.getenv("OIDC_RP_SCOPES") or "openid email profile").split()
    LOGIN_URL = "/oidc/authenticate/"
    LOGIN_REDIRECT_URL = "/dashboard/"
    LOGOUT_REDIRECT_URL = "/"

# Email (simulated by default; can be switched to real SMTP via .env)
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@smart-env-monitor.local")

EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = _env_int("EMAIL_PORT", 587)
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in {"1", "true", "yes"}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in {"1", "true", "yes"}
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

# Sensor configuration
THRESHOLD_VALUE = 100
SENSOR_STALE_MINUTES = _env_int("SENSOR_STALE_MINUTES", 30)
SENSOR_HEALTH_EMAIL_TO = (os.getenv("SENSOR_HEALTH_EMAIL_TO") or "").strip()

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", False)

SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = _env_int("SECURE_HSTS_SECONDS", 0 if DEBUG else 31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", False)

DEVICE_API_KEY = (os.getenv("DEVICE_API_KEY") or "").strip()

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {
        "sensor_ingest": os.getenv("THROTTLE_SENSOR_INGEST", "120/min"),
        "sensor_read": os.getenv("THROTTLE_SENSOR_READ", "600/min"),
    }
}

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

SENTRY_DSN = (os.getenv("SENTRY_DSN") or "").strip()
if SENTRY_DSN:
    try:
        traces_sample_rate = float((os.getenv("SENTRY_TRACES_SAMPLE_RATE") or "0").strip())
    except ValueError:
        traces_sample_rate = 0.0

    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=traces_sample_rate,
        send_default_pii=_env_bool("SENTRY_SEND_PII", False),
        environment=(os.getenv("SENTRY_ENVIRONMENT") or "development").strip(),
    )

CELERY_BROKER_URL = (os.getenv("CELERY_BROKER_URL") or "redis://localhost:6379/0").strip()
CELERY_RESULT_BACKEND = (os.getenv("CELERY_RESULT_BACKEND") or "redis://localhost:6379/0").strip()
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    "backend.services.notifications.send_email_task": {"queue": "notifications"},
}

CELERY_BEAT_SCHEDULE = {
    "check_sensor_health": {
        "task": "api.tasks.check_sensor_health",
        "schedule": _env_int("SENSOR_HEALTH_CHECK_INTERVAL_SECONDS", 300),
    }
}
