apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-env-monitor.fullname" . }}-celery-worker
  labels:
    {{- include "smart-env-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.celeryWorker }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smart-env-monitor.name" . }}
      app.kubernetes.io/component: celery-worker
  template:
    metadata:
      labels:
        {{- include "smart-env-monitor.labels" . | nindent 8 }}
        app.kubernetes.io/component: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "smart-env-monitor.fullname" . }}-config
            - secretRef:
                name: {{ include "smart-env-monitor.fullname" . }}-secret
          command: ["celery", "-A", "backend", "worker", "-l", "info"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-env-monitor.fullname" . }}-celery-beat
  labels:
    {{- include "smart-env-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.celeryBeat }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smart-env-monitor.name" . }}
      app.kubernetes.io/component: celery-beat
  template:
    metadata:
      labels:
        {{- include "smart-env-monitor.labels" . | nindent 8 }}
        app.kubernetes.io/component: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "smart-env-monitor.fullname" . }}-config
            - secretRef:
                name: {{ include "smart-env-monitor.fullname" . }}-secret
          command: ["celery", "-A", "backend", "beat", "-l", "info"]
