apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-env-monitor.fullname" . }}-secret
  labels:
    {{- include "smart-env-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
