# Generated by Django 6.0.2 on 2026-03-19 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incident_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='closed_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='IncidentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Skapad'), ('STATUS_CHANGED', 'Status ändrad'), ('ASSIGNED', 'Tilldelad')], max_length=40)),
                ('from_status', models.CharField(blank=True, choices=[('OPEN', 'Öppen'), ('IN_PROGRESS', 'Pågår'), ('CLOSED', 'Stängd')], default='', max_length=20)),
                ('to_status', models.CharField(blank=True, choices=[('OPEN', 'Öppen'), ('IN_PROGRESS', 'Pågår'), ('CLOSED', 'Stängd')], default='', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('from_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_audit_from_assignments', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='dashboard.incidentreport')),
                ('to_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_audit_to_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
